#!/usr/bin/env bash
set -euo pipefail

# Renders the template cask into a tap-ready cask in place: rewrites the
# `version` and `sha256` string literals and replaces the leading TEMPLATE
# header comment with a GENERATED one (#74 — the tap copy's values are real,
# so the template's "placeholders" claim must not ship with it).
# Shared by release.yml (tap mirror step) and scripts/bump-cask.sh (manual
# recovery). Fails unless exactly one of each literal is replaced and the
# file starts with the expected `# TEMPLATE` header.
#
#   scripts/render-cask.sh <cask-file> <version> <sha256>

[ $# -eq 3 ] || { echo "usage: $0 <cask-file> <version> <sha256>" >&2; exit 2; }
FILE="$1"; VERSION="$2"; SHA="$3"
[ -f "$FILE" ] || { echo "cask not found: $FILE" >&2; exit 1; }

python3 - "$FILE" "$VERSION" "$SHA" <<'PY'
import re, sys
path, version, sha = sys.argv[1:4]
s = open(path).read()
generated = (
    "# GENERATED by fr1j0/claude-light release.yml — do not edit by hand.\n"
    "# Source template: fr1j0/claude-light Casks/claude-light.rb\n"
)
s, nh = re.subn(r'\A# TEMPLATE[^\n]*\n(?:#[^\n]*\n)*', generated, s, count=1)
s, nv = re.subn(r'(\n[ \t]*version[ \t]+)"[^"]*"', r'\g<1>"%s"' % version, s, count=1)
s, ns = re.subn(r'(\n[ \t]*sha256[ \t]+)"[^"]*"', r'\g<1>"%s"' % sha, s, count=1)
if nh != 1 or nv != 1 or ns != 1:
    sys.exit("could not render %s (header hits=%d version hits=%d sha256 hits=%d)" % (path, nh, nv, ns))
open(path, "w").write(s)
PY
